### ISSUE TITLE
Módulo sale_early_payment_discount

### ISSUE THREAD

**Issue by parchanco** [Comunitea/external_modules#23]
Al aplicar un descuento por PP en la factura salta este error:

The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: account_id - account.id]

Hemos añadido una cuenta contable al producto de Early payment discount.

No sabemos si este error es por falta de parametrización o un fallo técnico.

**Comment by omar7r** [comment]
Posiblemente sea un fallo de configuración, hay un nuevo campo property en las categorías de productos, en el que hay que indicar cual es la cuenta contable sobre la que se va a imputar el pronto pago en los productos de esa categoría y posiblemente no esté rellenada, si vais al menú de properties, también la podéis poner por defecto en la property genérica y así ya aplica de forma automática a todas las categorías que existan.
