### ISSUE TITLE
Unexpired Unpaid Payments Field - Not work correctly !!

### ISSUE THREAD

**Issue by berctain** [Comunitea/external_modules#8]
Hi!
in risk management module when creating a invoice it show the "Unexpired Unpaid Payments" correctly, but in each time making a payment for that invoice it multiply "Unexpired Unpaid Payments" balance with payments frequency count, so if we have a invoice like 60.000 and made a 20.000 payment it should show 40.000 in Unexpired Unpaid Payments view, but it show 80.000 and if we made another payment transaction like 10.000 more, it will show 90.000 instead 30.000
i think it need to a review, looks like a simple bug

**Comment by omar7r** [comment]
Hi,

Update module and test again, maybe it was fixed in https://github.com/Comunitea/external_modules/commit/19fc1d80ea413f22e53ce0b8119c91184dbc0def

Regards.
